name: LoginSecurity
main: LoginSecurity\Ibenrm01\LoginSecurity
version: 1.4
api: 3.9.5
author: Ibenrm01

commands:
  login:
    description: Login Commands
  changepass:
    description: Change Password Commands
  rmpass:
    description: Remove Password Commands
  register:
    description: Register Commands
  mypass:
    description: Check My Password
  forgotpass:
    description: Forgot Your Password ?