---
##############
# CONFIG.YML #
##############
# AUTHOR: Ibenrm01

# MESSAGE: LOGIN
success.login: "§aSuccess Logged in, §dWelcome to server!"
please.login: "§b/login (password)"
already.login: "§aYou has been logged in"
password.wrong.login: "§cYou Password is wrong"
please.register.login: "§cYou unregistered, §bplease /register (password) (repeat-password)"

# MESSAGE: REGISTER
unregistered.register: "§bplease /register (password) (repeat-password)"
already.register: "§aYou has been register"
success.register: "§aSuccess registered, §dWelcome to server!"

# MESSAGE: CHANGE PASSWORD
success.changepass: "§aSuccess change passwords!"
can't-same.changepass: "§cPlease repeat §dCHANGE PASSWORD §cyou old password must be the same"

# MESSAGE: FORGOT PASSWORD
please-forgot.password: "§bplease /forgotpass"
#success-recovery.password = {password} = send your password
success-forgot.password: "§aSuccess Quest Forgot password, Your password: §d{password}"
wrong.answer: "§cAnswer there is wrong"

# COOLDOWN: REMOVE PASS AND CHANGE PASS | per seconds
remove.pass.cooldown: 120
change.pass.cooldown: 500
...
