---
##############
# CONFIG.YML #
##############
# AUTHOR: Ibenrm01

# MESSAGE: LOGIN
success.login: "§aSuccess Logged in, §dWelcome to server!"
please.login: "§b/login (password)"
already.login: "§aYou has been logged in"
password.wrong.login: "§cYou Password is wrong"
please.register.login: "§cYou unregistered, §bplease /register (password) (repeat-password)"

# MESSAGE: REGISTER
unregistered.register: "§bplease /register (password) (repeat-password)"
already.register: "§aYou has been register"
success.register: "§aSuccess registered, §dWelcome to server!"

# MESSAGE: CHANGE PASSWORD
success.changepass: "§aSuccess change passwords!"
can't-same.changepass: "§cPlease repeat §dCHANGE PASSWORD §cyou old password must be the same"
...